version: '3'
services:
  ipfs_host:
    image: ipfs/kubo:latest
    volumes:
      - ./ipfs/staging/:/export
      - ./ipfs/data:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    restart: always